version: "3.9"
services:
  mumbai_provider_1:
    ports:
      - "15500:15500"
      - "15600:15600"
    environment:
      - HTTPS_PORT=15600
      - HTTP_PORT=15500
    build: golem_service_provider
    user: root
    env_file:
      - node_conf.env

